package:
  name: stainwarpy
  version: "0.1.6"

source:
  path: ..

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  host:
    - python >=3.11
    - pip
    - setuptools
    - numpy 2.2.6
    - scipy 1.16.3
    - scikit-image 0.25.2
    - imagecodecs 2025.11.11
    - tifffile 2025.5.10
  run:
    - python >=3.11
    - numpy 2.2.6
    - scipy 1.16.3
    - scikit-image 0.25.2
    - imagecodecs 2025.11.11
    - tifffile 2025.5.10
    - typer 0.20.0

about:
  home: "https://github.com/tckumarasekara/stainwarpy"
  license: MIT
  summary: "Tools for image registration between multiplexed and HnE stained tissue images"
