{% set name = "stainwarpy" %}
{% set version = "0.1.6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/tckumarasekara/{{ name }}/releases/tag/v{{ version }}/stainwarpy-{{ version }}.tar.gz
  sha256: d19dc11ce752dcee6fee31675b0abdbaf9a893040aa9aa1074eab53713f4e4ba

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.11,<3.13
    - pip
    - setuptools

  run:
    - python >=3.11,<3.13
    - numpy ==2.2.6
    - scipy ==1.16.3
    - scikit-image ==0.25.2
    - imagecodecs ==2025.11.11
    - tifffile ==2025.5.10
    - typer ==0.20.0


test:
  imports:
    - stainwarpy
  commands:
    - stainwarpy --help

about:
  home: https://github.com/tckumarasekara/stainwarpy
  license: MIT
  license_file: LICENSE
  summary: "Tools for image registration between multiplexed and H&E stained tissue images"

extra:
  recipe-maintainers:
    - tckumarasekara
